name: Deploy To EC2

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload firewall.sh to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: firewall.sh
          target: /home/${{ secrets.EC2_USERNAME }}/firewall.sh

      - name: SSH into EC2 instance to run script and restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            chmod +x /home/${{ secrets.EC2_USERNAME }}/firewall.sh
            sudo /home/${{ secrets.EC2_USERNAME }}/firewall.sh
            sudo systemctl restart nginx
